spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true               # 开启从注册中心动态创建路由的功能，利用服务名进行路由
          lower-case-service-id: true # 将请求路径上的服务名配置为小写
      routes: # id和uri的服务名需要一致否则接口文档无法访问
        - id: message-server
          uri: lb://message-server
          predicates:
            - Path=/message-server/**
          filters:
            - StripPrefix=1 # 重定向 去掉message前缀

        - id: system-server
          uri: lb://system-server
          predicates:
            - Path=/system-server/**
          filters:
            - StripPrefix=1

        - id: bush-auth-server
          uri: lb://bush-auth-server
          predicates:
            - Path=/auth-server/**
          filters:
            - StripPrefix=1

    sentinel:
      enabled: true # 自动化配置是否生效
      eager: true # 禁用控制台懒加载
      transport:
        dashboard: 127.0.0.1:8858 # 控制台地址
      #        port: 18091 # 启动该服务，会在应用程序的相应服务器上启动HTTP Server，并且该服务器将与Sentinel dashboard进行交互
      # nacos配置持久化
#      datasource:
#        ds1:
#          nacos:
#            server-addr: 127.0.0.1:8848
#            dataId: sentinel-gateway
#            groupId: DEFAULT_GROUP
#            data-type: json
#            rule-type: flow

gateway:
  auth:
    # 忽略安全认证的url
    ignoreUrls:
      # 登陆
      - /oauth/token
      # swagger
      - /doc.html
      - /v2/api-docs
      - /swagger-resources
      - /swagger
      # 静态资源
      - /*/*.js
      - /*/*.css
      - /*/*.png
      - /*/*.ico
      # 通用接口
      - /commons

