spring:
  main:
    allow-circular-references: true

# Logger Config
logging:
  level:
    com.bushro.system.mapper: debug


# 阿里云配置
oss:
  path-style-access: false #使用云OSS 需要关闭
  endpoint: xxx #对应上图 ③ 处配置
  access-key: xxx # 上文创建的AK
  secret-key: xxx # 上文创建的SK
  bucketName: xxx # 上文创建的桶名称

file:
  prefix: https://bushro-oos.oss-cn-beijing.aliyuncs.com
